name: q_bot
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  google_fonts: ^2.3.2
  lottie: ^1.2.2
  flutter_spinkit: ^5.1.0
  flutter_ringtone_player: ^3.2.0
  flutter_svg: ^1.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/
  - assets/img/
  - assets/svg/
  - assets/json/
  - assets/sound/
  

